version: "3.8"

services:
  backend:
    build: ./Flask-API
    ports:
     - "5000:5000"
    environment:
      - API_ENV=production
    networks:
      - comparison-tool-network

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend 
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://backend:5000/  
    networks:
      - comparison-tool-network
networks:
  comparison-tool-network:
   driver: bridge